Change Unique key on albumthing to add thing_type (#187)
LibrePhotos/librephotos pull request #192
Opened 2021-03-08 20:47 UTC by tomamplius

Change Unique key on albumthing to add thing_type #187

2021-03-20 11:41 UTC, derneuere commented
I think the change in album_thing.py is missing:
https://github.com/LibrePhotos/librephotos/blob/072270b6482859f93189619f2b3dc3ddff556383/api/models/album_thing.py#L17-L18

2021-03-20 12:05 UTC, tomamplius commented
Ok, we need to migrate to UniqueConstraint?
https://docs.djangoproject.com/en/3.1/ref/models/options/#unique-together
> unique_together. unique_together may be deprecated in the future.

2021-03-20 17:30 UTC, derneuere requested changes
Found a couple of things that could be improved :)

2021-03-20 17:30 UTC, derneuere commented on api/migrations/0004_fixAlbumThingContraint.py
> +api/migrations/0004_fixAlbumThingContraint.py
I am not sure why this is at the start of the file. But it leads to an error

2021-03-20 17:30 UTC, derneuere commented on api/migrations/0004_fixAlbumThingContraint.py
> +               fields=['room', 'date'],
There is no field called "room" or "date" 😅

2021-03-20 17:30 UTC, derneuere commented on api/migrations/0004_fixAlbumThingContraint.py
> +
I forget it always too, but the name scheme in python is always with underscores. Please rename the file to 0004_fix_album_thing_constraint.py

2021-03-21 18:14 UTC, derneuere commented
Looks good :+1:

2021-03-21 18:14 UTC, merged